name = "js-playground" # 這是 Worker 的名字
main = "src/index.js"
compatibility_date = "2024-05-11"
compatibility_flags = ["nodejs_compat"]

browser = { binding = "BROWSER" }

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "js-playground"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "web-knowledge-index" # 直接用你帳號裡現成的！

[ai]
binding = "AI"
