name: Create Vector Index
on: workflow_dispatch

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create Index
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: vectorize create js-playground --dimensions=1024 --metric=cosine
